package com.kingzcheung.xime.ui.settings

object SettingsRoutes {
    const val Main = "main"
    const val Schema = "schema"
    const val Market = "market"
    const val MarketModel = "market_model"
    const val MarketPlugins = "market_plugins"
    const val SchemaLocal = "schema_local"
    const val ModelLocal = "model_local"
    const val SchemaMarketDetail = "schema_market_detail/{schemeId}"
    const val ModelMarketDetail = "model_market_detail/{modelId}"
    const val PluginMarketDetail = "plugin_market_detail/{pluginId}"
    const val LayoutMarketDetail = "layout_market_detail/{layoutId}"
    const val Theme = "theme"
    const val KeyEffect = "key_effect"
    const val LayoutDisplay = "layout_display"
    const val Dictionary = "dictionary"
    const val Plugins = "plugins"
    const val PluginSettings = "plugin_settings"
    const val SmartPrediction = "smart_prediction"
    const val SpeechToText = "speech_to_text"
    const val About = "about"
    const val Developer = "developer"
    const val StorageSpace = "storage_space"
    const val Privacy = "privacy"
    const val Licenses = "licenses"
    const val LogViewer = "log_viewer"
    const val HandwritingCapture = "handwriting_capture"
    const val ClipboardSync = "clipboard_sync"
    const val Backup = "backup"
    const val SchemaDictBrowser = "schema_dict_browser"
    const val RimeFileBrowser = "rime_file_browser"
}
